language: csharp
solution: ./GladNetV2.sln
sudo: required

install:
  - sudo apt-get install nunit-console
  - nuget restore ./GladNetV2.sln

before_script:
  - chmod +x ./lib/BuildDependencies.sh

script:
  - pwd
  - cd "$TRAVIS_BUILD_DIR/lib"
  - ./BuildDependencies.sh
  - cd "$TRAVIS_BUILD_DIR"
  - xbuild ./GladNetV2.sln
  - nunit-console ./tests/GladNet.Common.Tests/bin/Debug/GladNet.Common.Tests.dll
  - nunit-console ./tests/GladNet.Server.Common.Tests/bin/Debug/GladNet.Server.Common.Tests.dll